CREATE TABLE `user_ffg` (
  `id`          INT          NOT NULL AUTO_INCREMENT,
  `nama`        VARCHAR(255) NOT NULL,
  `distrik`     VARCHAR(255),
  `hsa`         VARCHAR(255),
  `sto`         VARCHAR(255),
  `id_telegram` VARCHAR(255),
  PRIMARY KEY (`id`)
);

-- 50 dummy records
INSERT INTO `user_ffg` (`nama`, `distrik`, `hsa`, `sto`, `id_telegram`) VALUES
('Agus Salim',         'Bandung Barat',  'HSA-01', 'STO-BDG1',  '@agussalim'),
('Budi Hartono',       'Bandung Timur',  'HSA-02', 'STO-BDG2',  '@budihartono'),
('Citra Dewi',         'Bandung Selatan','HSA-01', 'STO-BDG3',  '@citradewi'),
('Dani Wijaya',        'Cimahi',         'HSA-03', 'STO-CMH1',  '@daniwijaya'),
('Eka Putri',          'Cimahi',         'HSA-03', 'STO-CMH2',  '@ekaputri'),
('Fahri Ramadan',      'Bandung Utara',  'HSA-02', 'STO-BDG4',  '@fahriramadan'),
('Gilang Saputra',     'Garut',          'HSA-04', 'STO-GRT1',  '@gilangsaputra'),
('Hana Kusuma',        'Garut',          'HSA-04', 'STO-GRT2',  '@hanakusuma'),
('Irwan Susanto',      'Sumedang',       'HSA-05', 'STO-SMD1',  '@irwansusanto'),
('Joko Prabowo',       'Sumedang',       'HSA-05', 'STO-SMD2',  '@jokoprabowo'),
('Kartini Lestari',    'Tasikmalaya',    'HSA-06', 'STO-TSM1',  '@kartinilestari'),
('Lukman Hakim',       'Tasikmalaya',    'HSA-06', 'STO-TSM2',  '@lukmanhakim'),
('Maya Sari',          'Cianjur',        'HSA-07', 'STO-CJR1',  '@mayasari'),
('Nanda Pratama',      'Cianjur',        'HSA-07', 'STO-CJR2',  '@nandapratama'),
('Oscar Firmansyah',   'Sukabumi',       'HSA-08', 'STO-SKB1',  '@oscarfirmansyah'),
('Putri Handayani',    'Sukabumi',       'HSA-08', 'STO-SKB2',  '@putrihandayani'),
('Qori Rahmawati',     'Bogor',          'HSA-09', 'STO-BGR1',  '@qorirahmawati'),
('Rizal Fauzi',        'Bogor',          'HSA-09', 'STO-BGR2',  '@rizalfauzi'),
('Sinta Nurhayati',    'Bogor Barat',    'HSA-09', 'STO-BGR3',  '@sintanurhayati'),
('Teguh Santoso',      'Depok',          'HSA-10', 'STO-DPK1',  '@teguhsantoso'),
('Umar Bakri',         'Depok',          'HSA-10', 'STO-DPK2',  '@umarbakri'),
('Vina Oktaviani',     'Bekasi',         'HSA-11', 'STO-BKS1',  '@vinaoktaviani'),
('Wahyu Nugroho',      'Bekasi',         'HSA-11', 'STO-BKS2',  '@wahyunugroho'),
('Xenia Permata',      'Bekasi Utara',   'HSA-11', 'STO-BKS3',  '@xeniapermata'),
('Yudi Firmawan',      'Karawang',       'HSA-12', 'STO-KRW1',  '@yudifirmawan'),
('Zara Nabila',        'Karawang',       'HSA-12', 'STO-KRW2',  '@zaranabila'),
('Adi Kurniawan',      'Purwakarta',     'HSA-13', 'STO-PWK1',  '@adikurniawan'),
('Bella Anggraini',    'Purwakarta',     'HSA-13', 'STO-PWK2',  '@bellaanggraini'),
('Cahya Prasetyo',     'Subang',         'HSA-14', 'STO-SBG1',  '@cahyaprasetyo'),
('Dina Amalia',        'Subang',         'HSA-14', 'STO-SBG2',  '@dinaamalia'),
('Eko Wicaksono',      'Indramayu',      'HSA-15', 'STO-IDR1',  '@ekowicaksono'),
('Fira Susanti',       'Indramayu',      'HSA-15', 'STO-IDR2',  '@firasusanti'),
('Guntur Mahesa',      'Cirebon',        'HSA-16', 'STO-CRB1',  '@gunturmahesa'),
('Hesti Wulandari',    'Cirebon',        'HSA-16', 'STO-CRB2',  '@hestiwulandari'),
('Imam Buchari',       'Cirebon Timur',  'HSA-16', 'STO-CRB3',  '@imambuchari'),
('Jihan Fadhilah',     'Majalengka',     'HSA-17', 'STO-MJL1',  '@jihanfadhilah'),
('Kevin Andrean',      'Majalengka',     'HSA-17', 'STO-MJL2',  '@kevinandrean'),
('Laila Rosyidah',     'Kuningan',       'HSA-18', 'STO-KNG1',  '@lailarosyidah'),
('Muhamad Yusuf',      'Kuningan',       'HSA-18', 'STO-KNG2',  '@muhamadyusuf'),
('Nita Rahayu',        'Bandung Utara',  'HSA-02', 'STO-BDG5',  '@nitarahayu'),
('Opik Sopiandi',      'Bandung Barat',  'HSA-01', 'STO-BDG6',  '@opiksopiandi'),
('Pandu Wibowo',       'Cimahi Utara',   'HSA-03', 'STO-CMH3',  '@panduwibowo'),
('Qila Amara',         'Garut Selatan',  'HSA-04', 'STO-GRT3',  '@qilaamara'),
('Rendi Saputra',      'Tasikmalaya',    'HSA-06', 'STO-TSM3',  '@rendisaputra'),
('Sari Dewi',          'Ciamis',         'HSA-19', 'STO-CMS1',  '@saridewi'),
('Taufik Hidayat',     'Ciamis',         'HSA-19', 'STO-CMS2',  '@taufikhidayat'),
('Ulfa Hairani',       'Banjar',         'HSA-20', 'STO-BNJ1',  '@ulfahairani'),
('Vicky Prasetya',     'Banjar',         'HSA-20', 'STO-BNJ2',  '@vickyprasetya'),
('Wendi Kurniadi',     'Pangandaran',    'HSA-20', 'STO-PNG1',  '@wendikurniadi'),
('Yeni Marlina',       'Pangandaran',    'HSA-20', 'STO-PNG2',  '@yenimarlina');
